swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      #produces:
       # - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  #----------------------------------------- Ajout des Endpoints-------------------------------------#
  
  # Obtenir toutes les transactions provenant d'un compte spécifique.
  /{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags: 
        - User Transaction
      summary: Transactions by Specific Account
      Description : API for getting all transactions in specific account
      Responses :
      '200' :
        Description : User transactions retrieved successfully
        Shema :
          $ref : '#/definitions/ApiResponse'
      '400' :
        Description : Invalid Fields
      '500' :
        Description : Internal Server Error
  # Obtenir une transaction spécifique.
  /transactions/{transactionId}:
    get:
      security:
        - Bearer: []
      tags: 
        - User Transaction
      summary: API for Specific transaction
      Description : getting specific transaction
      parameters:
        - name: body
          in: body
          description: ID of the transaction to retrieve
          required: true
          schema:
            $ref: '#/definitions/Description'
          type: string
      Responses :
      '200' :
        Description : User specific transaction retrieved successfully
        Shema :
          $ref : '#/definitions/ApiResponse'
      '400' :
        Description : Invalid Fields
      '500' :
        Description : Internal Server Error
  
    put:
      security: 
        - Bearer: []
      tags:
        - User Transaction
      summary: Specific Transaction API
      description: API for updating or add a specific transaction
      parameters:
        - in: body
          name: body
          description: Update transaction attributes
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: The transaction information has been updated successfully.
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  # Mettre à jour une information dans une transaction spécifique.
  #----------------------------------------- Ajout des Endpoints-------------------------------------#
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
      userName:
        type: string
        description: user public name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      userName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
      description:
        type: string
  Description:
    type: object
    properties:
      status:
        type: integer
      body:
        type: object
        properties:
          id:
            type: string
          Description:
            type: string